steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sm-gemini-playground/document-processing-ui', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sm-gemini-playground/document-processing-ui']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'document-processing-ui', '--image', 'gcr.io/sm-gemini-playground/document-processing-ui', '--region', 'europe-north1','--allow-unauthenticated', '--platform', 'managed', '--memory', '500Mi', '--max-instances', '5', '--update-env-vars', 'API=']
images:
- gcr.io/sm-gemini-playground/document-processing-ui